[tool.ruff]
line-length = 88              # Максимальная длина строки

[tool.ruff.lint]
fixable = ["E501", "F401", "W293"]  # Правила, которые можно автоматически исправить
select = ["E", "F", "W"]  # Включаемые коды правил
   
