[tool.ruff]
line-length = 88              # Максимальная длина строки
select = ["E", "F", "W"]      # Включаемые коды правил
fixable = ["F", "E501"]       # Правила, которые можно автоматически исправить
